# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --cov
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: coverage-badge
        name: coverage-badge
        entry: poetry run coverage-badge -o coverage.svg -f
        language: system
        always_run: true
        pass_filenames: false
