"""Trace fixtures for the TypeScript conformance reader (spec §11.4, T13).

``tests/fixtures/traces/generated`` is regenerated by ``generate.py`` and compared by canonical content, not by
bytes. ``tests/fixtures/traces/frozen`` is committed once and never regenerated; its expected JSON is checked
against the reference Python reader here, and the TypeScript suite (``pnpm -C studio test``) checks the other
reader against the same files. Nothing here needs Node.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

from simulatte.trace import Trace

TRACES = Path(__file__).resolve().parents[1] / "fixtures" / "traces"
GENERATED = TRACES / "generated"
FROZEN = TRACES / "frozen"


def _generate_module() -> ModuleType:
    spec = importlib.util.spec_from_file_location("trace_fixture_generate", TRACES / "generate.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _expected(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_generated_fixtures_canonically_up_to_date(tmp_path: Path) -> None:
    # A fresh interpreter: the fixtures record the registered entity kinds, which other tests extend.
    subprocess.run([sys.executable, str(TRACES / "generate.py"), "--out", str(tmp_path)], check=True, timeout=120)
    generate = _generate_module()

    committed = sorted(p.name for p in GENERATED.glob("*.simtrace"))
    assert committed, "no generated fixtures are committed"
    assert sorted(p.name for p in tmp_path.glob("*.simtrace")) == committed
    assert sorted(p.name for p in tmp_path.glob("*.expected.json")) == sorted(
        p.name for p in GENERATED.glob("*.expected.json")
    )
    for name in committed:
        # Text, not parsed values: in Python -0.0 == 0.0 and 1 == 1.0, so only the canonical text can tell a reader
        # that collapses them from one that does not (ruling R12). The generated fixtures are RNG-free, so their
        # content does not depend on the interpreter or the platform.
        fresh = generate.dump(generate.canonical_content(tmp_path / name))
        assert fresh == generate.dump(generate.canonical_content(GENERATED / name)), name
        expected = name.removesuffix(".simtrace") + ".expected.json"
        assert _text(tmp_path / expected) == _text(GENERATED / expected), expected
        assert generate.dump(generate.expected_document(GENERATED / name)) == _text(GENERATED / expected), expected


def test_generated_fixtures_use_explicit_seeds() -> None:
    generate = _generate_module()
    for name, seed in generate.SEEDS.items():
        trace = Trace.open(GENERATED / f"{name}.simtrace")
        assert trace.manifest["seed"] == str(seed), name
        expected = _expected(GENERATED / f"{name}.expected.json")
        assert expected["seed"] == str(seed)
    assert {p.name.removesuffix(".simtrace") for p in GENERATED.glob("*.simtrace")} == set(generate.SEEDS)


def test_frozen_fixtures_match_the_reference_reader() -> None:
    generate = _generate_module()
    names = sorted(p.name for p in FROZEN.glob("*.simtrace"))
    assert {
        "default_seed.simtrace",
        "hostile_keys.simtrace",
        "nonfinite.simtrace",
        "trailerless.simtrace",
        "truncated.simtrace",
    } <= set(names)
    for name in names:
        document = generate.expected_document(FROZEN / name)
        expected = FROZEN / (name.removesuffix(".simtrace") + ".expected.json")
        assert generate.dump(document) == _text(expected), name  # text: -0.0 and 1.0 must not collapse


def test_frozen_fixtures_cover_the_hard_cases() -> None:
    default_seed = _expected(FROZEN / "default_seed.expected.json")
    assert isinstance(default_seed["seed"], str) and int(default_seed["seed"]) >= 2**53  # needs a decimal string
    assert Trace.open(FROZEN / "truncated.simtrace").truncated
    assert Trace.open(FROZEN / "trailerless.simtrace").truncated

    hostile = json.dumps(_expected(FROZEN / "hostile_keys.expected.json"))
    for key in ("__proto__", "constructor", "prototype", "~x", "~__proto__"):
        assert json.dumps(key) + ":" in hostile, key
